// generated by quant/pack.py — golem SDRAM image offsets (32-bit words)
localparam int MEM_HDR = 0;
localparam int MEM_EXP_LUT = 8;
localparam int MEM_OUT_NORM_GAIN = 520;
localparam int MEM_POS_EMB = 584;
localparam int MEM_TOK_EMB = 16968;
localparam int MEM_LAYERS = 279112;
localparam int MEM_LAYER_STRIDE = 168144;
localparam int MEM_KV_BASE = 1624264;
