import numpy as np

from mind import config
from quant import quantize  # noqa: F401  (ensures quant importable)

# The SDRAM image: everything golem.sv reads, as 32-bit words, in the exact order
# the hardware consumes it. Word = 4 int8 weights (little-endian) OR one 31b mult
# OR one 6b shift. Layout offsets are emitted to golem_mem.svh so RTL and packer agree.

W_ORDER = ["wq", "wk", "wv", "wo", "up", "down"]          # weight stream order (block FSM)
PARAM_ORDER = ["wq", "wk", "wv", "wo", "up", "down"]      # per-channel requant order (pbase)
SCALARS = ["attn_norm", "mlp_norm", "sm", "att", "r2_in", "r2_out", "r3_in", "r3_out"]


def pack_i8(arr):
    u = arr.astype(np.int8).reshape(-1, 4).view(np.uint8).astype(np.uint32)
    return u[:, 0] | (u[:, 1] << 8) | (u[:, 2] << 16) | (u[:, 3] << 24)


class Writer:
    def __init__(self):
        self.words = []
        self.off = {}

    def mark(self, name):
        self.off[name] = len(self.words)

    def u32(self, vals):
        self.words.extend(int(v) & 0xFFFFFFFF for v in np.atleast_1d(vals).tolist())

    def scalar(self, m, s):
        self.u32([m, s])

    def i8(self, arr):
        self.u32(pack_i8(arr))


def build(q):
    w = Writer()
    w.mark("HDR")
    w.scalar(int(q["emb_tok.m"]), int(q["emb_tok.s"]))
    w.scalar(int(q["emb_pos.m"]), int(q["emb_pos.s"]))
    w.scalar(int(q["out_norm.m"]), int(q["out_norm.s"]))
    while len(w.words) < 8:
        w.u32([0])

    w.mark("EXP_LUT")
    w.u32(q["exp_lut"])
    w.mark("OUT_NORM_GAIN")
    w.i8(q["out_norm.w"])
    w.mark("POS_EMB")
    w.i8(q["pos_emb.w"])
    w.mark("TOK_EMB")
    w.i8(q["tok_emb.w"])

    w.mark("LAYERS")
    layer_stride = None
    for li in range(config.N_LAYERS):
        p = f"layers.{li}."
        start = len(w.words)
        for name in SCALARS:
            w.scalar(int(q[p + name + ".m"]), int(q[p + name + ".s"]))
        for name in PARAM_ORDER:
            ms, ss = q[p + name + ".m"], q[p + name + ".s"]
            for i in range(len(ms)):
                w.scalar(int(ms[i]), int(ss[i]))
        w.i8(q[p + "attn_norm.w"])
        w.i8(q[p + "mlp_norm.w"])
        w.i8(q[p + "gelu_lut"])
        for name in W_ORDER:
            w.i8(q[p + name + ".w"])
        if layer_stride is None:
            layer_stride = len(w.words) - start
    w.off["LAYER_STRIDE"] = layer_stride
    return w


def emit_svh(off, path):
    lines = ["// generated by quant/pack.py — golem SDRAM image offsets (32-bit words)"]
    for k, v in off.items():
        lines.append(f"localparam int MEM_{k} = {v};")
    path.write_text("\n".join(lines) + "\n")


def main():
    from pathlib import Path

    data = Path(config.DATA_DIR)
    q = dict(np.load(data / "golem_int8.npz"))
    w = build(q)
    hexpath = data / "golem_mem.hex"
    with open(hexpath, "w") as f:
        f.write("\n".join(f"{v:08x}" for v in w.words) + "\n")
    emit_svh(w.off, Path("rtl") / "golem_mem.svh")
    mb = len(w.words) * 4 / 1e6
    print(f"packed {len(w.words):,} words = {mb:.2f} MB -> {hexpath}")
    print(f"layer stride {w.off['LAYER_STRIDE']:,} words; offsets -> rtl/golem_mem.svh")
    for k, v in w.off.items():
        print(f"  {k:16s} {v:,}")


if __name__ == "__main__":
    main()
